CREATE DATABASE junitavatardb;
USE junitavatardb;

DROP TABLE CLUB_APNS_TOKEN;
DROP TABLE CLUB_AMENITIES;
DROP TABLE BEACONS;
drop  TABLE BEACON_USERS;

CREATE TABLE CLUB_APNS_TOKEN (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_AMENITY_ID INT(10) REFERENCES CLUB_AMENITIES(ID) ON DELETE CASCADE,
	APNS_TOKEN VARCHAR(100) NOT NULL,	
	CREATE_DATE DATETIME 
);
--AVAILABLE_DATE_TIMEnot sure about this!  might get dropped.

;

CREATE TABLE CLUB_AMENITIES (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
	AMENITYID VARCHAR(50) NOT NULL UNIQUE,
	IMAGE_ID INT(10) REFERENCES IMAGES(ID),
	DESCRIPTION VARCHAR(100) ,
	HOURS_OPERATION_NOTE VARCHAR(100) ,
	AVAILABLE_DATE_TIME DATETIME, 
	CREATE_DATE DATETIME 
);

CREATE TABLE BEACONS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	BEACONID VARCHAR(50) NOT NULL UNIQUE,
	CLUB_ID INT(10)  REFERENCES CLUBS(ID) ON DELETE CASCADE,
	AMENITY_ID INT(10)  REFERENCES CLUB_AMENITIES(ID),
	LOCATION VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) ,
	DEPARTMENT VARCHAR(100),
	INSTALLATION_STAFF_ID INT(10) REFERENCES USERS(ID),
	CREATE_DATE DATETIME 
);
CREATE INDEX BEACONS_BEACONID_IDX ON BEACONS (BEACONID);

CREATE TABLE BEACON_USERS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	BEACON_ID INT(10)  REFERENCES BEACONS(ID),
	USER_ID INT(10) REFERENCES USERS(ID),
	CREATE_DATE DATETIME 
);
CREATE INDEX BU_BEACONID_IDX ON BEACON_USERS (BEACON_ID);
CREATE INDEX BU_USERID_IDX ON BEACON_USERS (USER_ID);


insert into CLUBS (ID, CLUBID, NAME, PHONE_NUMBER, CREATE_DATE) VALUES (1, 'pharaoh1', 'Pharaoh Gentlemen''s Club', '123-1234', NOW());
insert into CLUB_AMENITIES (ID, CLUB_ID, AMENITYID, DESCRIPTION, AVAILABLE_DATE_TIME, HOURS_OPERATION_NOTE,CREATE_DATE) 
VALUES (1, 1, 'pharoah1-Bar', 'The Bar in the Pharoah''s Club', NOW(), 'Opens daily, 10am until 11pm, Weekend 10am until 3am', NOW());

delete from BEACONS;
insert into BEACONS (ID, BEACONID, CLUB_ID, AMENITY_ID, LOCATION, DESCRIPTION, DEPARTMENT, CREATE_DATE)
VALUES (1, 'Beacon1', 1, 1, 'Downtown LA', 'Restaurant Beacon', 'Restaurant', NOW());

commit;


--- 3/28
--alter table CLUB_AMENITIES change column  AMENITYID VARCHAR(50) UNIQUE NOT NULL;
