CREATE DATABASE avatardb;
USE avatardb;

drop TABLE SURVEY_ANSWERS;
drop TABLE SURVEYS;


CREATE TABLE SURVEYS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
	CLUB_AMENITY_ID INT(10) REFERENCES CLUB_AMENITIES(ID) ON DELETE CASCADE,
	QUESTION_A VARCHAR(100),
	QUESTION_B VARCHAR(100),
	CREATE_DATE DATETIME 
);
create index SURVEY_IND_CLUB_ID on SURVEYS(CLUB_ID, CLUB_AMENITY_ID);
INSERT INTO SURVEYS VALUES (1, 1, 1, 'How did you like your food?', 'How did you rate the music', NOW());
DROP TABLE SURVEY_ANSWERS;
CREATE TABLE SURVEY_ANSWERS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	SURVEY_ID INT(10) REFERENCES SURVEYS(ID),
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
	CLUB_AMENITY_ID INT(10) REFERENCES CLUB_AMENITIES(ID) ON DELETE CASCADE,
	MEMBER_ID INT(10) REFERENCES USERS(ID) ON DELETE CASCADE,
	BEACON_ID INT(10) REFERENCES BEACONS(ID) ON DELETE CASCADE,
	SURVEY_ANS VARCHAR(1) DEFAULT 'Y' ,
	ANS_PART_A INT(10) ,
	ANS_PART_B INT(10) ,
	CREATE_DATE DATETIME,  
	ANSWERED_ON DATETIME  
);
create index SA_IND_USERID on SURVEY_ANSWERS (MEMBER_ID, CLUB_ID, CREATE_DATE, SURVEY_ID);