-- 4/4
-- Applied to ec2
CREATE TABLE AMENITY_EMPLOYEE (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_AMENITY_ID INT(10)  REFERENCES CLUB_AMENITIES(ID),
	USER_ID INT(10) REFERENCES USERS(ID),
	CREATE_DATE DATETIME 
);
CREATE INDEX SA_AMENITYID_IDX ON AMENITY_EMPLOYEE (CLUB_AMENITY_ID, USER_ID);
CREATE INDEX SA_AMENITYID_IDX2 ON AMENITY_EMPLOYEE (USER_ID, CLUB_AMENITY_ID);


