--ran on aws 2/08/2016
create table TOKEN_CACHE (
	ID INT(10) NOT NULL  PRIMARY KEY,
	TOKEN VARCHAR(50) NOT NULL,
	VALID_TILL TIMESTAMP NOT NULL,
	USER_ID INT(10) NOT NULL REFERENCES USERS(ID)
);

CREATE INDEX TOKEN_CACHE_IND1 on TOKEN_CACHE (TOKEN, USER_ID);
CREATE INDEX TOKEN_CACHE_IND2 on TOKEN_CACHE (VALID_TILL);

