insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Alabama','AL');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Alaska','AK');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Arizona','AZ');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Arkansas','AR');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('California','CA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Colorado','CO');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Connecticut','CT');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Delaware','DE');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Florida','FL');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Georgia','GA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Hawaii','HI');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Idaho','ID');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Illinois','IL');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Indiana','IN');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Iowa','IA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Kansas','KS');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Kentucky','KY');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Louisiana','LA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Maine','ME');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Maryland','MD');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Massachusetts','MA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Michigan','MI');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Minnesota','MN');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Mississippi','MS');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Missouri','MO');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Montana','MT');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Nebraska','NE');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Nevada','NV');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('New Hampshire','NH');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('New Jersey','NJ');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('New Mexico','NM');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('New York','NY');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('North Carolina','NC');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('North Dakota','ND');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Ohio','OH');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Oklahoma','OK');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Oregon','OR');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Pennsylvania','PA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Rhode Island','RI');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('South Carolina','SC');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('South Dakota','SD');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Tennessee','TN');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Texas','TX');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Utah','UT');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Vermont','VT');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Virginia','VA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Washington','WA');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('West Virginia','WV');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Wisconsin','WI');
insert into REF_STATES(STATE_NAME, STATE_ABBR) values ('Wyoming','WY');
commit;
