-- Ran on aws 12/13/2015.
DROP TABLE REF_STATES;

-- Ran on aws 12/13/2015.
CREATE TABLE REF_STATES (
	STATE_ABBR  VARCHAR(2) NOT NULL PRIMARY KEY,
	STATE_NAME VARCHAR(50) NOT NULL
);
-- Ran on aws 12/13/2015.
INSERT INTO REF_STATES VALUES ('CA', 'California');
INSERT INTO REF_STATES VALUES ('VA', 'Virginia');

-- Ran on aws 12/13/2015.
DROP TABLE REF_COUNTRY;
CREATE TABLE REF_COUNTRY (
	COUNTRY_CODE  VARCHAR(5) NOT NULL PRIMARY KEY,
	COUNTRY_NAME VARCHAR(50) NOT NULL
);
-- Ran on aws 12/13/2015.
INSERT INTO REF_COUNTRY VALUES ('USA', 'UNITED STATES OF AMERICA');
COMMIT;

-- Ran on aws 12/13/2015.
DROP TABLE CLUB_GEO_LOCATION;
-- Ran on aws 12/13/2015.
alter table CLUBS add (
    X_COORD VARCHAR(25),
	Y_COORD VARCHAR(25),
	STATE_ABBR  VARCHAR(2) REFERENCES REF_STATE(STATE_ABBR),
	COUNTRY_CODE  VARCHAR(5) REFERENCES REF_COUNTRY(COUNTRY_CODE)
);
-- Ran on aws 12/13/2015.
update CLUBS set STATE_ABBR = STATE;
-- Ran on aws 12/13/2015.
alter table CLUBS drop column state;

--36S1A
-- Ran on aws 11/7/2015.
ALTER TABLE CLUB_AMENITIES ADD AMENITY_NAME VARCHAR(50);

-- Ran on aws 12/13/2015.
CREATE TABLE AMENITY_BLACKOUT (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
	AMENITY_ID INT(10) REFERENCES CLUB_AMENITIES(ID) ON DELETE CASCADE,
    BLACKOUT_DATE DATE,
    BLACKOUT_HOURS VARCHAR(48) DEFAULT 'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN' 
);
    /* BY 30 MIN MARKER INCREMENT STARTING WITH MIDNIGHT. X MARKS BLACKOUT NNNNNNNNNNNNNNNNNNNNXXXXXXXXXXNNNNNNNNNNNNNNNNNN   */
    /* ABOVE EX: IS BLACKOUT STARTS 11AM THRU 3PM */

/*Test data*/
insert into AMENITY_BLACKOUT values (1, 1, 1, NOW(), 'NNNNNNNNNNNNNNNNNNNNNNNNNNNYYYYNNNNNNNNNNNNNNNNN');

-- Ran on aws 12/13/2015.
CREATE TABLE CLUB_KEYS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
    KEYCODE VARCHAR(10) NOT NULL UNIQUE
);


/* Ran on aws 11/28 */
ALTER TABLE USERS ADD (NOTICED_FLAG VARCHAR(1) DEFAULT 'N');

/* Ran on aws 11/28 */
ALTER TABLE USERS ADD (LINKED_ACCOUNT_ID INT(10) REFERENCES USERS(ID));

/* Ran on aws 11/28 */
ALTER TABLE USERS ADD (ACTIVATION_DATE DATETIME);

/* Ran on aws 11/28 */
ALTER TABLE USERS ADD (SUSPENDED_DATE DATETIME);

/* Ran on aws 11/28 */
CREATE TABLE USER_NOTES (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	USER_ID INT(10) REFERENCES USERS(ID),
    NOTE_TEXT VARCHAR(250) NOT NULL,
    NOTE_DATE DATETIME NOT NULL
);

-- Ran on aws 12/13/2015.
CREATE TABLE USER_RESERVATIONS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	RESERVATION_NUMBER VARCHAR(100) NOT NULL UNIQUE,
	USER_ID INT(10) REFERENCES USERS(ID),
    CLUB_ID INT(10) REFERENCES CLUBS(ID),
    AMENITY_ID INT(10) REFERENCES CLUB_AMENITIES(ID),
    NO_PERSONS INT(10) DEFAULT 1,
    RESERVATION_DATE DATETIME 
);


-- Ran on aws 12/13/2015.
ALTER TABLE CLUB_AMENITIES ADD (BODY_TEXT VARCHAR(250));
-- Ran on aws 12/13/2015.
ALTER TABLE CLUB_AMENITIES ADD (HEADER_TEXT VARCHAR(250));
-- Ran on aws 12/13/2015.
ALTER TABLE CLUB_AMENITIES ADD (SECONDARY_HEADER_TEXT VARCHAR(250));
-- Ran on aws 12/13/2015.
ALTER TABLE CLUBS ADD (BODY_TEXT VARCHAR(250));
-- Ran on aws 12/13/2015.
ALTER TABLE CLUBS ADD (HEADER_TEXT VARCHAR(250));

/* test data only */
update CLUB_AMENITIES set BODY_TEXT = DESCRIPTION;
update CLUB_AMENITIES set HEADER_TEXT = Concat('Header text for ', DESCRIPTION);
update CLUB_AMENITIES set SECONDARY_HEADER_TEXT = Concat('Secondary header text for ', DESCRIPTION);
update CLUBS set BODY_TEXT = Concat('Body of ', NAME);
update CLUBS set HEADLINE_TEXT = Concat('Headline of ', NAME);
