CREATE TABLE REF_STATES (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	STATE_ABBR  VARCHAR(2) NOT NULL,
	STATE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE REF_COUNTRY (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	COUNTRY_CODE  VARCHAR(5) NOT NULL,
	COUNTRY_NAME VARCHAR(50) NOT NULL
);
INSERT INTO REF_COUNTRY VALUES (1, 'USA', 'UNITED STATES OF AMERICA');
COMMIT;

CREATE TABLE CLUB_GEO_LOCATION (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
	X_COORD VARCHAR(25),
	Y_COORD VARCHAR(25),
	STATE_ID INT (10) REFERENCES REF_STATES,
	COUNTRY_ID  INT(10) REFERENCES REF_COUNTRY,

	ADDRESS VARCHAR(100),
	ZIPCODE VARCHAR(10),
	CITY VARCHAR(50)	
);

INSERT INTO CLUB_GEO_LOCATION select ID, ID, null, null, STATE_ID, 1, ADDRESS, ZIPCODE, CITY
FROM CLUBS, REF_STATES
WHERE REF_STATES.STATE_NAME = CLUBS.STATE;

--36S1A
ALTER TABLE CLUB_AMENITIES ADD AMENITY_NAME VARCHAR(50);

CREATE TABLE AMENITY_BLACKOUT (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	AMENITY_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
    BLACKOUT_DATE DATE,
    BLACKOUT_HOURS VARCHAR(48) DEFAULT 'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN', /* BY 30 MIN MARKER INCREMENT STARTING WITH MIDNIGHT. X MARKS BLACKOUT NNNNNNNNNNNNNNNNNNNNXXXXXXXXXXNNNNNNNNNNNNNNNNNN   */
    							/* ABOVE EX: IS BLACKOUT STARTS 11AM THRU 3PM */
);



CREATE TABLE CLUB_KEYS (
	ID    INT(10) NOT NULL PRIMARY KEY, /*PK*/
	CLUB_ID INT(10) REFERENCES CLUBS(ID) ON DELETE CASCADE,
    KEYCODE VARCHAR(10) NOT NULL UNIQUE
);


ALTER TABLE USERS ADD (NOTICED_FLAG VARCHAR(1) DEFAULT 'N');

ALTER TABLE USERS ADD (LINKED_ACCOUNT_ID INT(10) REFERENCES USERS(ID));


